services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: ${MARIADB_IMAGE}
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - wp_db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - stack_net

  adminer:
    build:
      context: ./requirements/adminer
    image: ${ADMINER_IMAGE}
    container_name: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=${DATABASE_SERVER}
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - stack_net

  wordpress:
    build:
      context: ./requirements/wordpress
    image: ${WORDPRESS_IMAGE}
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=${DATABASE_SERVER}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PORT=${MARIADB_PORT}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - WORDPRESS_SITE_URL=${WORDPRESS_SITE_URL}
      - WORDPRESS_SITE_TITLE=${WORDPRESS_SITE_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL}
      - WORDPRESS_USER_PASS=${WORDPRESS_USER_PASS}
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - stack_net

  nginx:
    build:
      context: ./requirements/nginx
    image: ${NGINX_IMAGE}
    container_name: nginx
    environment:
      - DOMAIN=${DOMAIN}
      - UPSTREAM=${UPSTREAM}
      - GENERATE_SELF_SIGNED=${GENERATE_SELF_SIGNED}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - ./requirements/nginx/certs:/etc/nginx/certs
      - wp_data:/var/www/html:ro
    depends_on:
      - wordpress
      - adminer
    restart: unless-stopped
    networks:
      - stack_net

volumes:
  wp_db:
    name: ${WORDPRESS_DB_VOLUME}
  wp_data:
    name: ${WORDPRESS_DATA_VOLUME}

networks:
  stack_net:
    name: ${STACK_NETWORK}
    driver: bridge